### ISSUE TITLE
es5.github.com → es5.github.io

### ISSUE THREAD

**Issue by mathiasbynens** [es5/es5.github.io#28]
- [ ] Rename this repository from `es5.github.com` to `es5.github.io` to match the new URL (GitHub will set up a redirect from the old name to the new one)
- [ ] Any other references to `es5.github.com` should be changed to `es5.github.io` to avoid confusion

**Comment by johanbove** [comment]
So, not to be impolite, but it's been a couple of years now since last reply.
I guess this issue can be closed or revised somehow?
